# Generated by Django 5.2.16 on 2026-08-12 20:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiche_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('id_number', models.CharField(max_length=50, verbose_name='N° CNI / Passeport')),
                ('address', models.CharField(max_length=255, verbose_name='Adresse')),
                ('agent_name', models.CharField(blank=True, max_length=150, verbose_name='Agent responsable')),
                ('status', models.CharField(choices=[('PENDING', "En attente d'activation"), ('ACTIVE', 'Actif'), ('REJECTED', 'Refusé'), ('CLOSED', 'Clôturé')], default='PENDING', max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='savings_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('DEPOSIT', 'Dépôt'), ('WITHDRAWAL', 'Retrait')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01, 'Le montant doit être supérieur à 0')])),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('CONFIRMED', 'Confirmé'), ('REJECTED', 'Rejeté')], default='PENDING', max_length=10)),
                ('previous_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('new_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('note', models.TextField(blank=True, verbose_name='Observations')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='savings.savingsaccount')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['account'], name='savings_sav_account_6176e5_idx')],
            },
        ),
    ]
