# Generated by Django 5.2.16 on 2026-08-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='service',
            field=models.CharField(choices=[('transfert', "Transfert d'argent"), ('epargne', 'Épargne'), ('autre', 'Autre')], default='transfert', max_length=20),
        ),
    ]
