# Generated by Django 5.2.16 on 2026-09-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_contactmessage_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_handled',
            field=models.BooleanField(default=False, verbose_name='Traité'),
        ),
    ]
