# Generated by Django 5.2.16 on 2026-09-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_contactmessage_is_handled'),
        ('marketing', '0006_agency'),
    ]

    operations = [
    ]
